openapi: 3.0.3
info:
  title: PlayStation Portable - OpenAPI 3.0
  description: |-
    hmmmmm.
  version: 1.0.11
tags:
  - name: order
    description: test
  - name: employee
  - name: reservation
  - name: transaction
  - name: surcharge
  - name: tax
  - name: discount
  - name: merchant
paths:
  /order:
    put:
      tags:
        - order
      summary: update an order
      requestBody:
        description: test
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
        required: true
      responses:
        '200':
          description: Successful operation
  /order/{orderId}:
    get:
      parameters:
        - name: orderId
          in: path
          description: ID of order to return
          required: true
          schema:
            type: integer
            format: int64
      tags:
        - order
      responses:
        '200':
          description: Successful operation
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        creationDateTime:
          type: string
          format: date-time
        orderOwner:
          type: integer
          format: int64
          example: 5
        orderStatus:
          type: string
          example: open
        tip:
          type: number
          format: float
          example: 6.4
        receiptStatus:
          type: string
          example: printed