openapi: 3.0.3
info:
  title: PlayStation Portable - OpenAPI 3.0
  description: |-
    This is the API documentation for the system design course at Vilnius University. The creators team name is PlayStation Portable.
  version: 1.0.11
tags:
  - name: order
  - name: employee
  - name: permission
  - name: reservation
  - name: transaction
  - name: surcharge
  - name: tax
  - name: discount
  - name: merchant
paths:
  /order:
    put:
      tags:
        - order
      summary: Update an order
      requestBody:
        description: An order object that is to be updated.  
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
        required: true
      responses:
        '200':
          description: Successful operation
    post:
      tags:
        - order
      summary: Create an order
      requestBody:
        description: An order object that is to be created.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
        required: true
      responses:
        '200':
          description: Successful operation
  /order/{orderId}:
    get:
      parameters:
        - name: orderId
          in: path
          description: Finds a specific order by its ID
          required: true
          schema:
            type: integer
      tags:
        - order
      summary: Find order by ID
      responses:
        200:
          description: Successful operation
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
    delete:
      parameters:
        - name: orderId
          in: path
          description: Deletes a specific order by its ID
          required: true
          schema:
            type: integer
      tags:
        - order
      summary: Delete order by ID
      responses:
        200:
          description: Successful operation
  /order/{EmployeeId}:
    get:
      parameters:
        - name: EmployeeId
          in: path
          description: Find all orders by their owner
          required: true
          schema:
            type: integer
      tags:
        - order
      summary: Find all orders by their owner
      responses:
        200:
          description: Successful operation
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/OrderArray'
  /order/{OrderStatus}:
    get:
      parameters:
        - name: OrderStatus
          in: path
          description: Finds orders with a status
          required: true
          schema:
            type: string
      tags:
        - order
      summary: Find orders by status
      responses:
        200:
          description: Successful operation
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/OrderArray'
  /surcharge:
    put:
      tags:
        - surcharge
      summary: Update a surcharge
      requestBody:
        description: A surcharge object that is to be updated.  
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Surcharge'
        required: true
      responses:
        '200':
          description: Successful operation
    post:
      tags:
        - surcharge
      summary: Create a surcharge
      requestBody:
        description: A surcharge object that is to be created.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Surcharge'
        required: true
      responses:
        '200':
          description: Successful operation
    get:
      tags:
        - surcharge
      summary: Get all surcharges
      responses:
        200:
          description: Successful operation
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/SurchargeArray'
  /surcharge/{surchargeId}:
    get:
      parameters:
        - name: surchargeId
          in: path
          description: Finds a specific surcharge by its ID
          required: true
          schema:
            type: integer
      tags:
        - surcharge
      summary: Find surcharge by ID
      responses:
        200:
          description: Successful operation
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Surcharge'
    delete:
      parameters:
        - name: surchargeId
          in: path
          description: Deletes a specific surcharge by its ID
          required: true
          schema:
            type: integer
      tags:
        - surcharge
      summary: Delete surcharge by ID
      responses:
        200:
          description: Successful operation
  /surcharge/{surchargeStatus}:
    get:
      parameters:
        - name: surchargeStatus
          in: path
          description: Finds surcharges with a status
          required: true
          schema:
            type: string
      tags:
        - surcharge
      summary: Find surcharges by status
      responses:
        200:
          description: Successful operation
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/SurchargeArray'
  /discount:
    put:
      tags:
        - discount
      summary: Update a discount
      requestBody:
        description: A discount object that is to be updated.  
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Discount'
        required: true
      responses:
        '200':
          description: Successful operation
    post:
      tags:
        - discount
      summary: Create a discount
      requestBody:
        description: A discount object that is to be created.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Discount'
        required: true
      responses:
        '200':
          description: Successful operation
    get:
      tags:
        - discount
      summary: Get all discounts
      responses:
        200:
          description: Successful operation
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/DiscountArray'
  /discount/{discountId}:
    get:
      parameters:
        - name: discountId
          in: path
          description: Finds a specific discount by its ID
          required: true
          schema:
            type: integer
      tags:
        - discount
      summary: Find discount by ID
      responses:
        200:
          description: Successful operation
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Discount'
    delete:
      parameters:
        - name: discountId
          in: path
          description: Deletes a specific discount by its ID
          required: true
          schema:
            type: integer
      tags:
        - discount
      summary: Delete discount by ID
      responses:
        200:
          description: Successful operation
  /discount/{discountStatus}:
    get:
      parameters:
        - name: discountStatus
          in: path
          description: Finds discounts with a status
          required: true
          schema:
            type: string
      tags:
        - discount
      summary: Find discounts by status
      responses:
        200:
          description: Successful operation
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/DiscountArray'
  /employee/{EmployeeId}:
    get:
      tags:
        - employee
      summary: Get an employee by ID (or the permissions of that employee)
      parameters:
        - name: EmployeeId
          in: path
          description: Employee ID
          required: true
          schema:
            type: integer
        - name: include
          in: query
          description: Get employee permissions
          schema:
            type: string
            enum: [permissions] 
      responses:
        '200':
          description: Successful operation
          content: 
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Employee' 
                  - $ref: '#/components/schemas/PermissionArray'
                discriminator:
                    propertyName: permissions  # Add a discriminator
                    mapping:
                      true: '#/components/schemas/PermissionArray'
                      false: '#/components/schemas/Employee'
    delete:
      parameters:
        - name: EmployeeId
          in: path
          description: Delete employee by ID
          required: true
          schema:
            type: number
      tags:
        - employee
      summary: Delete an employee object by Id
      responses:
        200:
          description: Successful operation
  /employee/{Status}:
    get:
      parameters:
        - name: Status
          in: path
          description: Find employee's by status
          required: true
          schema:
            type: number
      tags:
        - employee
      summary: Find employee's by status
      responses:
        200:
          description: Successful operation
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeArray'
  /employee/{Organisation}:
    get:
      parameters:
        - name: Organisation
          in: path
          description: Find employee's by organisation
          required: true
          schema:
            type: number
      tags:
        - employee
      summary: Find employee's by organisation
      responses:
        200:
          description: Successful operation
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeArray'
  /employee:
    post:
      tags:
        - employee
      summary: Create an employee
      requestBody:
        description: An employee object that is to be created.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
        required: true
      responses:
        '200':
          description: Successful operation
    put:
      tags:
        - employee
      summary: Update an employee
      requestBody:
        description: An employee object that is to be updated.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
        required: true
      responses:
        '200':
          description: Successful operation
  /permission:
    post:
      tags:
        - permission
      summary: Assign a permission
      requestBody:
        description: A permission object that is to be created.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Permission'
        required: true
      responses:
        '200':
          description: Successful operation
  /permission/{PermissionId}:
    delete:
      tags:
        - permission
      summary: Delete a permission
      parameters:
        - name: PermissionId
          in: path
          description: Delete permission
          required: true
          schema:
            type: number
      responses:
        200:
          description: Successful operation
components:
  schemas:
    Order:
      type: object
      properties:
        OrderId:
          type: number
          format: int64
          example: 10
        CreationDateTime:
          type: string
          format: date-time
        OrderOwner:
          type: number
          format: int64
          example: 5
        OrderStatus:
          type: string
          example: open
        Tip:
          type: number
          example: 6.4
        ReceiptStatus:
          type: string
          example: printed
        customerName:
          type: string
          example: John
        TableName:
          type: string
          example: By the window
        OrderType:
          type: string
          example: Dine in
    OrderArray:
      type: array
      items: 
        $ref: '#/components/schemas/Order'
    Discount:
      type: object
      properties:
        DiscountId:
          type: number
          format: int64
          example: 10
        Name:
          type: string
          example: special October offer
        Value:
          type: number
          example: 7.1
        Type:
          type: string
          example: Percentage
        CreationDateTime:
          type: string
          format: date-time
        Status:
          type: string
          example: Active
        TimeSensitive:
          type: string
          example: Yes
    Employee:
      type: object
      properties:
        EmployeeId:
          type: number
          format: int64
          example: 30
        Name:
          type: string
          example: John
        Role:
          type: string
          example: Cook
        CreationDateTime:
          type: string
          example: 20024-20-08 08:24
        Status:
          type: string
          example: Active
        Password:
          type: string
          example: 1234
        Organisation:
          type: number
          format: int64
          example: 50
    EmployeeArray:
      type: array
      items:
        $ref: '#/components/schemas/Employee'
    Permission:
      type: object
      properties:
        PermissionId:
          type: number
          format: int64
          example: 40
        PermissionTemplateId:
          type: number
          format: int64
          example: 50
        EmployeeId:
          type: number
          format: int64
          example: 50
        CreationDateTime:
          type: string
          example: 20024-20-08 08:59
    PermissionArray:
      type: array
      items:
        $ref: '#/components/schemas/Permission'
    DiscountArray:
      type: array
      items: 
        $ref: '#/components/schemas/Discount'
    Surcharge:
      type: object
      properties:
        SurchargeId:
          type: number
          format: int64
          example: 10
        Name:
          type: string
          example: surcharge1
        Value:
          type: number
          example: 7.1
        Type:
          type: string
          example: Percentage
        CreationDateTime:
          type: string
          format: date-time
        Status:
          type: string
          example: Active
        TimeSensitive:
          type: string
          example: Yes
    SurchargeArray:
      type: array
      items: 
        $ref: '#/components/schemas/Surcharge'
